kv_path = "/var/lib/backend/admin/data.kv"

[[services]]
name = "flatdb"
sock_path = "/var/run/flatdb.sock"
enabled = true
mon_interval_sec = 30

[admin]
log_sock_path = "/run/backup/admin.sock"
backup_chat_id = 0
backup_time = "03:00"

[tokens]
admin_tokens = []
backup_tokens = []

[bot]
en = true
token = ""
webhook_url = ""
